### ISSUE TITLE
experiencing lag when flowing fluid

### ISSUE THREAD

**Issue by podium868909** [tomalbrc/filament#10]
![image](https://github.com/user-attachments/assets/fca17115-3eb2-4fea-a92d-e61b6810054d)
![image](https://github.com/user-attachments/assets/55087e2d-59e0-4495-97f5-d8665f9f2a1c)

my server is experiencing random lag spikes and i managed to use spark to capture when it happened

Minecraft 1.21.1

Fabric API 0.106.0

Fabric Loader
0.16.7

filament
0.9.11

Polymer 0.9.18

**Comment by tomalbrc** [comment]
This should be fixed in 0.9.14 and later
