### ISSUE TITLE
Item texture not rendering?

### ISSUE THREAD

**Issue by SuperDZ555** [tomalbrc/filament#11]
As a quick test to see if the mod works, I added a little test item to my datapack. I'm not particularly worried about the name right now, as I'm sure it can be fixed easily (I've tinkered with translation files before). My main concern is the fact that the item is, for some reason, rendering as the pink and black missing texture cube.
![image](https://github.com/user-attachments/assets/8866fa6c-17ee-4422-ba3b-7902cb5088bc)
Here's the files:

data/despair/filament/item/despair_test_item.json
```
{
	"id": "despair:despair_test_item",
	"vanillaItem": "minecraft:paper",
	"itemResource": {
		"models": {
			"default": "minecraft:custom/item/test"
		}
	},
	"properties": {
		"lore": ["Wow! Lore!"]
	},
	"behaviour": {
		"execute": {
			"consumes": false,
			"command": "/tellraw @a [{\"color\":\"#FFFFFF\",\"text\":\"Y\"},{\"color\":\"#DFFFDF\",\"text\":\"i\"},{\"color\":\"#BFFFBF\",\"text\":\"p\"},{\"color\":\"#9FFF9F\",\"text\":\"p\"},{\"color\":\"#80FF80\",\"text\":\"e\"},{\"color\":\"#60FF60\",\"text\":\"e\"},{\"color\":\"#40FF40\",\"text\":\"!\"},{\"color\":\"#00FF00\",\"text\":\"!\"}]",
			"sound": "minecraft:block.copper_bulb.turn_on"
		}
	}
}
```

assets/minecraft/models/custom/item/test.json
```
{
  "parent": "minecraft:item/generated",
  "textures": {
    "layer0": "minecraft:item/test"
  }
}
```

assets/minecraft/textures/item/test.png
![test](https://github.com/user-attachments/assets/607f410d-187f-4436-b337-50b91bbfe97d)

I'm not sure what I'm doing wrong. I've tried `/polymer generate-pack` and doing F3+T and relaunching the game multiple times and it doesn't seem to show up.

Minecraft version: 1.21.3
Fabric loader version: 0.16.9
Fabric API version: 0.110.0+1.21.3
Fabric Language Kotlin version: 1.13.0+kotlin.2.1.0 (I'm not sure if it's relevant but I'll include it anyways)
Polymer version: 0.10.2+1.21.3
Filament version: 0.10.0+1.21.2

**Comment by tomalbrc** [comment]
The model needs to be in either `models/block` or `models/item`
So if you put your model in `assets/minecraft/models/item/custom/test.json` you would reference it as 
`"default": "minecraft:custom/test"` in the filament item config

**Comment by SuperDZ555** [comment]
It worked, thanks
