### ISSUE TITLE
Unable to specify correct tool for block

### ISSUE THREAD

**Issue by SuperDZ555** [tomalbrc/filament#12]
As is stated in the documents, the "requiredTool" variable is a boolean, meaning it is either true or false. However, there's no information on how to specify _which_ tool in particular (pickaxe, axe, etc.) is required to break the block fastest, and this vital information doesn't seem to be stated anywhere, not even the example datapack or the documents themselves.

**Comment by tomalbrc** [comment]
the tool is defined via block tags, like `mineable/pickaxe`

**Comment by SuperDZ555** [comment]
That makes sense. I don't know how I didn't think of that, considering I've messed with block tags before. Thanks!

**Comment by SuperDZ555** [comment]
Just tried it in-game, and it didn't work..? I'm pretty sure I did it correctly,
Here's the file structure:

data/minecraft/tags/mineable/pickaxe.json
```
{
  "values": [
    "grimstone:grimstone"
  ]
}
```

**Comment by tomalbrc** [comment]
should be in tags/item/mineable/pickaxe.json

**Comment by SuperDZ555** [comment]
Yep, it works now. Thanks again!
